services:
  receiver:
    build: ./receiver
    ports:
      - "8080:8080"
    depends_on:
      - "storage"

  storage:
    build: ./storage
    ports:
      - "8090:8090"
    expose:
      - '8090'
    depends_on:
      - "db"
      - "kafka"
      - "zookeeper"

  processing:
    build: ./processing
    network_mode: host
    depends_on:
      - "db"

  audit_log:
    build: ./audit_log
    ports:
      - "8110:8110"
    depends_on:
      - "processing"

  dashboard:
    build: ./dashboard
    ports:
      - "8888:80"
    depends_on:
      - "processing"
      - "audit_log"