services:
  receiver:
    build: ../receiver
    ports:
      - "8080"
    hostname: receiver
    volumes:
      - /home/azureuser/config/receiver:/config
      - /home/azureuser/logs/:/logs
    networks:
      - "api.network"
    depends_on:
      - "storage"
      - "kafka"

  storage:
    build: ../storage
    ports:
      - "8090"
    hostname: storage
    volumes:
      - /home/azureuser/config/storage:/config
      - /home/azureuser/logs/:/logs
    expose:
      - '8090'
    networks:
      - "api.network"
    depends_on:
      - "db"
      - "kafka"
      - "zookeeper"

  processing:
    build: ../processing 
    volumes:
      - /home/azureuser/config/processing:/config
      - /home/azureuser/logs/:/logs
      - processing-db:/data
    hostname: processing
    ports:
      - "8100"
    networks:
      - "api.network"
    depends_on:
      - "db"

  audit_log:
    build: ../audit_log
    volumes:
      - /home/azureuser/config/audit_log:/config
      - /home/azureuser/logs/:/logs
    ports:
      - "8110"
    networks:
      - "api.network"
    hostname: audit_log
    depends_on:
      - "processing"

  event_logger:
    build: ../event_logger
    volumes:
      - /home/azureuser/config/event_logger:/config
      - /home/azureuser/logs/:/logs
      - logging-db:/data
    ports:
      - "8120"
    networks:
      - "api.network"
    hostname: event_logger
    depends_on:
      - "processing"
      - "receiver"
      - "storage"

  dashboard:
    build: ../dashboard-ui
    ports:
      - "3000"
    networks:
      - "api.network"
    depends_on:
      - "processing"
      - "audit_log"

  nginx:
    image: nginx:latest
    volumes:
      - /azureuser/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "receiver"
      - "storage"
      - "processing"
      - "audit_log"
      - "dashboard"
    ports:
      - "80:80"
    networks:
      - "api.network"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    volumes:
      - /home/azureuser/zookeeper/data:/opt/zookeeper-3.4.13/data
    hostname: zookeeper
    networks:
      - "api.network"

  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    expose:
      - '9092'
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1,event_log:1:1" #topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_BROKER_ID: 1
    networks:
      - "api.network"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/azureuser/kafka:/kafka/kafka-logs
    depends_on:
      - zookeeper

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'events'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306'
    networks:
      - "api.network"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
  processing-db:
  logging-db:

networks:
  api.network: